"""Migration / SQL scaffold generators for the RLS migration assistant.

These four generators turn a concrete :class:`~django_tenants.rls.models.TenantRLSModel`
(or, for third-party tables, a bare table name) into ready-to-edit text a human
can drop into an app's ``migrations/`` directory or run with ``psql``. They are
the "GENERATE" tier of the assistant (``manage.py rls_doctor --generate``): they
return strings only and **write nothing**, leaving placement and review to the
operator.

Each generator composes the existing primitives rather than re-deriving the DDL:

* :func:`enable_rls_migration` emits a migration using
  :class:`~django_tenants.rls.operations.EnableRLS` +
  :class:`~django_tenants.rls.operations.CreateTenantPolicy` (Step 6).
* :func:`staged_fk_migration` emits the staged tenant-FK migration text for
  Step 3/5: ``AddField`` with ``null=True``, a commented ``RunPython`` backfill
  STUB (Step 4 is app-specific and DANGEROUS -- never auto-generated runnable),
  and a clearly-delimited ``AlterField`` to ``null=False`` gated on the backfill
  having completed (Step 5).
* :func:`third_party_policy_sql` emits raw ENABLE/FORCE + CREATE POLICY DDL for a
  table you cannot subclass (e.g. ``authtoken_token``), Step 7. Its USING /
  WITH CHECK clauses come straight from
  :meth:`~django_tenants.rls.policies.TenantPolicy.get_using_expression` /
  :meth:`~django_tenants.rls.policies.TenantPolicy.get_check_expression` so the
  DDL is byte-identical to what the framework's schema editor would emit.
* :func:`unique_constraint_migration` emits ``AddConstraint`` of a
  tenant-scoped ``UniqueConstraint`` + ``RemoveConstraint`` of the old one
  (Step 8).

All Django imports are lazy (inside the functions) so importing this module stays
cheap and free of app-registry side effects, matching the rest of this package.
"""


# Marker the assistant/docs/tests look for: backfill is Step 4, app-specific and
# DANGEROUS, so the generated RunPython is always a commented-out STUB.
_BACKFILL_TODO = "TODO(step-4): backfill"


def _model_idents(model):
    """Return the identifiers a migration/DDL needs from a model.

    Returns ``(app_label, model_name, object_name, db_table, label)``. Kept in
    one place so every generator references the model's ``_meta`` consistently.
    """
    meta = model._meta
    return (
        meta.app_label,
        meta.model_name,
        meta.object_name,
        meta.db_table,
        meta.label,
    )


def staged_fk_migration(model):
    """Return migration text for the staged tenant-FK rollout (Steps 3-5).

    The text is a single, self-contained migration *module* that performs the
    safe, non-destructive parts of adding the tenant FK:

    1. ``AddField`` of the tenant ``ForeignKey`` with ``null=True`` so the column
       can be added to a populated table without a table rewrite or a NOT NULL
       violation (Step 3);
    2. a commented-out ``RunPython`` backfill STUB -- the actual backfill (Step 4)
       is cross-schema and entirely app-specific, so it is **never** emitted as
       runnable code; the operator must write and review it;
    3. a clearly-delimited ``AlterField`` flipping the column to ``null=False``
       (Step 5), gated by a comment instructing the operator to move it into a
       *separate* migration that runs only *after* the backfill is verified.

    The migration imports and ``dependencies`` are placeholders the operator
    fills in (the latest migration of the app, plus the tenant model's app).
    """
    from django.conf import settings
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    field = conf.tenant_field()
    tenant_model = settings.TENANT_MODEL

    return '''\
"""Staged tenant-FK rollout for {label} (RLS migration Steps 3-5).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber/rename to follow your latest migration.

This file is a SCAFFOLD. It performs ONLY the safe, non-destructive parts:

  * Step 3: add the tenant FK as ``null=True`` (no table rewrite, no NOT NULL
    violation on an already-populated table).
  * Step 5: an ``AlterField`` to ``null=False`` is included but commented out --
    SPLIT IT INTO A SEPARATE MIGRATION and apply it ONLY AFTER the Step 4
    backfill below has run and you have verified there are no NULL ``{field}_id``
    rows. Applying NOT NULL before the backfill will fail.

The Step 4 backfill is cross-schema and entirely app-specific (DANGEROUS): it is
left as a commented ``RunPython`` STUB for you to implement and review. The
assistant never generates runnable backfill code.
"""

from django.conf import settings
from django.db import migrations, models


# {backfill_todo} the existing rows so every {db_table} row gets the correct
# tenant before the column is made NOT NULL. This is app-specific -- you must map
# each legacy per-schema row to its owning tenant. Implement and review, then
# uncomment the RunPython operation below.
#
# def backfill_tenant(apps, schema_editor):
#     Model = apps.get_model("{app_label}", "{object_name}")
#     # ... map each row to its tenant and set obj.{field}_id ...
#     raise NotImplementedError("Implement the {label} tenant backfill (Step 4).")
#
# def reverse_backfill(apps, schema_editor):
#     # Usually a no-op: clearing the FK would re-create unscoped rows.
#     pass


class Migration(migrations.Migration):

    # TODO: set these to your app's latest migration and the tenant model's app.
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
        migrations.swappable_dependency(settings.TENANT_MODEL),
    ]

    operations = [
        # Step 3: add the tenant FK as NULLABLE so it can be added safely to an
        # already-populated table. matches TenantRLSModel's FK (CASCADE, indexed).
        migrations.AddField(
            model_name="{model_name}",
            name="{field}",
            field=models.ForeignKey(
                to={tenant_model!r},
                on_delete=models.CASCADE,
                db_index=True,
                related_name="+",
                null=True,
            ),
        ),

        # Step 4 (DANGEROUS, app-specific): run the backfill defined above. Keep
        # this COMMENTED until you have implemented and reviewed backfill_tenant.
        # migrations.RunPython(backfill_tenant, reverse_backfill),

        # ---------------------------------------------------------------------
        # Step 5: flip the column to NOT NULL. {backfill_todo} MUST be complete
        # and verified (zero NULL {field}_id rows) BEFORE you apply this. Move
        # this AlterField into its OWN, LATER migration that depends on the
        # backfill migration -- do not apply it in the same step as the backfill.
        # ---------------------------------------------------------------------
        # migrations.AlterField(
        #     model_name="{model_name}",
        #     name="{field}",
        #     field=models.ForeignKey(
        #         to={tenant_model!r},
        #         on_delete=models.CASCADE,
        #         db_index=True,
        #         related_name="+",
        #         null=False,
        #     ),
        # ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        object_name=object_name,
        db_table=db_table,
        field=field,
        tenant_model=tenant_model,
        backfill_todo=_BACKFILL_TODO,
    )


def enable_rls_migration(model):
    """Return migration text enabling RLS + the tenant policy (Step 6).

    Emits a migration whose operations are
    :class:`~django_tenants.rls.operations.EnableRLS` and
    :class:`~django_tenants.rls.operations.CreateTenantPolicy` for the model.
    ``CreateTenantPolicy`` snapshots the tenant field and PK cast at authoring
    time (see its docstring), so the rendered migration is a deterministic record
    of the policy DDL.

    This is the same DDL the safe ``--fix`` / ``model.enable_rls()`` path applies;
    generating it as a migration lets a project that prefers migration-managed
    schema changes carry the enable step in version control instead.
    """
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    field = conf.tenant_field()
    pk_cast = conf.get_tenant_pk_cast()

    return '''\
"""Enable RLS + tenant-isolation policy on {label} (RLS migration Step 6).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber to follow your latest migration.

Apply this ONLY after the {db_table} table has a NOT NULL ``{field}_id`` column
and has been backfilled (Steps 3-5). EnableRLS additionally applies FORCE ROW
LEVEL SECURITY when TENANT_RLS_FORCE is true, so the policy also constrains the
table owner. CreateTenantPolicy builds the same default
TenantPolicy(tenant_field="{field}", pk_cast="{pk_cast}") the framework's
auto-enable path creates, so this is byte-identical to the runtime policy.
"""

from django.db import migrations

from django_tenants.rls import operations as rls_operations


class Migration(migrations.Migration):

    # TODO: set this to your app's latest migration (the one that made
    # {field}_id NOT NULL).
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
    ]

    operations = [
        rls_operations.EnableRLS("{model_name}"),
        rls_operations.CreateTenantPolicy(
            "{model_name}",
            tenant_field="{field}",
            pk_cast="{pk_cast}",
        ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        db_table=db_table,
        field=field,
        pk_cast=pk_cast,
    )


def third_party_policy_sql(table, *, pk_cast="integer"):
    """Return raw ENABLE/FORCE + CREATE POLICY DDL for a third-party ``table``.

    For a table you cannot make inherit ``TenantRLSModel`` (e.g.
    ``authtoken_token``), this emits the same DDL the framework's schema editor
    would emit for the default tenant policy, so the third-party table is policed
    identically to a first-party one (Step 7).

    The USING / WITH CHECK expressions are taken verbatim from
    :meth:`~django_tenants.rls.policies.TenantPolicy.get_using_expression` /
    :meth:`~django_tenants.rls.policies.TenantPolicy.get_check_expression` (the
    InitPlan scalar sub-SELECT form), so the policy is byte-for-byte the framework
    policy. The table is assumed to carry a ``<tenant_field>_id`` column.

    ``pk_cast`` is the Postgres cast suffix matching the tenant model's PK type
    (one of ``integer`` / ``bigint`` / ``uuid`` / ``text``); pass the value from
    ``conf.get_tenant_pk_cast()`` when in doubt. It defaults to ``"integer"`` for
    the common ``AutoField`` / ``BigAutoField``-but-integer case.
    """
    from . import conf
    from .models import _default_policy_name
    from .policies import TenantPolicy

    field = conf.tenant_field()
    policy_name = _default_policy_name(table)
    policy = TenantPolicy(name=policy_name, tenant_field=field, pk_cast=pk_cast)

    using = policy.get_using_expression()
    check = policy.get_check_expression()

    # Mirror RLSSchemaEditorMixin.create_policy exactly: AS PERMISSIVE FOR ALL TO
    # public, USING (...) WITH CHECK (...). Identifiers are quoted with double
    # quotes (Postgres standard); the expressions are reused verbatim so they are
    # identical to the framework policy. FORCE matches TENANT_RLS_FORCE's default
    # of true -- without it the table owner silently bypasses the policy.
    return '''\
-- Tenant-isolation RLS policy for third-party table "{table}" (RLS migration Step 7).
--
-- Generated by ``manage.py rls_doctor --generate``. Review, then apply with psql
-- or wrap in a migration RunSQL. This DDL is byte-identical to the policy the
-- framework's schema editor creates for a first-party TenantRLSModel: the
-- USING / WITH CHECK expressions come straight from TenantPolicy, so "{table}"
-- is policed exactly like a managed table.
--
-- Assumes "{table}" has a "{field}_id" column referencing the tenant PK (cast
-- {pk_cast}). Drop any existing same-named policy first so this is re-runnable.

ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY;
-- FORCE so the policy also applies to the table owner role:
ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "{policy_name}" ON "{table}";

CREATE POLICY "{policy_name}" ON "{table}"
    AS PERMISSIVE FOR ALL TO public
    USING ({using})
    WITH CHECK ({check});
'''.format(
        table=table,
        field=field,
        pk_cast=pk_cast,
        policy_name=policy_name,
        using=using,
        check=check,
    )


def unique_constraint_migration(model, fields):
    """Return migration text making a UNIQUE constraint tenant-scoped (Step 8).

    PostgreSQL checks UNIQUE constraints with RLS bypassed, so a UNIQUE that omits
    the tenant enforces uniqueness across ALL tenants and leaks cross-tenant row
    existence (check W005). This emits an ``AddConstraint`` of a new
    ``UniqueConstraint`` spanning ``[tenant_field, *fields]`` and a
    ``RemoveConstraint`` of the old, tenant-blind constraint.

    ``fields`` is the offending field set (the tuple from
    ``checks._unique_fieldsets``); the tenant field is prepended (and not
    duplicated if already present). The names of the new and old constraints are
    derived deterministically but flagged as TODOs because the old name depends on
    how the original constraint was declared (a ``unique_together`` /
    ``unique=True`` has an auto-generated name you must look up).
    """
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    tenant = conf.tenant_field()

    field_list = list(fields)
    # Prepend the tenant field, never duplicating it if the caller already has it.
    scoped = [tenant] + [f for f in field_list if f != tenant]

    scoped_repr = ", ".join(repr(f) for f in scoped)
    suffix = "_".join(field_list) if field_list else "unique"
    new_name = "%s_%s_per_tenant_uniq" % (db_table, suffix)
    # Postgres identifiers cap at 63 bytes; keep the generated name short enough.
    new_name = new_name[:63]

    return '''\
"""Make the UNIQUE on {label} tenant-scoped (RLS migration Step 8).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber to follow your latest migration.

PostgreSQL checks UNIQUE constraints with RLS BYPASSED, so the existing UNIQUE on
{fields!r} enforces uniqueness across ALL tenants and leaks cross-tenant row
existence. This migration replaces it with a tenant-scoped UniqueConstraint over
{scoped!r}.

TODO: also update the model's Meta so makemigrations agrees with this state:
remove the old unique=True / unique_together / UniqueConstraint and add
``models.UniqueConstraint(fields=[{scoped_repr}], name="{new_name}")``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    # TODO: set this to your app's latest migration.
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
    ]

    operations = [
        # Add the tenant-scoped UNIQUE first so uniqueness is never unenforced.
        migrations.AddConstraint(
            model_name="{model_name}",
            constraint=models.UniqueConstraint(
                fields=[{scoped_repr}],
                name="{new_name}",
            ),
        ),
        # Then drop the old, tenant-blind constraint.
        # TODO: replace "<old_constraint_name>" with the real name. For a
        # Meta.constraints UniqueConstraint it is the declared name; for a
        # unique_together / unique=True it is the auto-generated name Django gave
        # it (inspect with: python manage.py sqlmigrate {app_label} <migration>,
        # or query pg_constraint on "{db_table}").
        migrations.RemoveConstraint(
            model_name="{model_name}",
            name="<old_constraint_name>",
        ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        db_table=db_table,
        fields=tuple(field_list),
        scoped=tuple(scoped),
        scoped_repr=scoped_repr,
        new_name=new_name,
    )
