"""Migration / SQL scaffold generators for the RLS migration assistant.

These four generators turn a concrete :class:`~django_tenants.rls.models.TenantRLSModel`
(or, for third-party tables, a bare table name) into ready-to-edit text a human
can drop into an app's ``migrations/`` directory or run with ``psql``. They are
the "GENERATE" tier of the assistant (``manage.py rls_doctor --generate``): they
return strings only and **write nothing**, leaving placement and review to the
operator.

Each generator composes the existing primitives rather than re-deriving the DDL:

* :func:`enable_rls_migration` emits a migration using
  :class:`~django_tenants.rls.operations.EnableRLS` +
  :class:`~django_tenants.rls.operations.CreateTenantPolicy` (Step 6).
* :func:`staged_fk_migration` emits the staged tenant-FK migration text for
  Step 3/5: ``AddField`` with ``null=True``, a commented ``RunPython`` backfill
  STUB (Step 4 is app-specific and DANGEROUS -- never auto-generated runnable),
  and a clearly-delimited ``AlterField`` to ``null=False`` gated on the backfill
  having completed (Step 5).
* :func:`third_party_policy_sql` emits raw ENABLE/FORCE + CREATE POLICY DDL for a
  table you cannot subclass (e.g. ``authtoken_token``), Step 7. Its USING /
  WITH CHECK clauses come straight from
  :meth:`~django_tenants.rls.policies.TenantPolicy.get_using_expression` /
  :meth:`~django_tenants.rls.policies.TenantPolicy.get_check_expression` so the
  DDL is byte-identical to what the framework's schema editor would emit. It emits
  the *policy* only and assumes the tenant column already exists.
* :func:`isolate_external_table_sql` emits the FULL ordered prerequisite sequence
  for such a table -- ADD COLUMN with a GUC-reading DEFAULT + tenant FK, a backfill
  STUB, an optional ``SET NOT NULL``, UNIQUE rewrites, then the policy -- and points
  at :class:`~django_tenants.rls.operations.IsolateExternalTable`, the reversible
  migration operation that performs the same sequence.
* :func:`unique_constraint_migration` emits ``AddConstraint`` of a
  tenant-scoped ``UniqueConstraint`` + ``RemoveConstraint`` of the old one
  (Step 8).

All Django imports are lazy (inside the functions) so importing this module stays
cheap and free of app-registry side effects, matching the rest of this package.
"""

# ``_quote_ident`` lives in operations.py (its canonical home -- the reversible
# migration operations that emit the same DDL use it too). Import it here so the
# raw third-party / external-table DDL these generators interpolate stays quoted
# identically, without duplicating the Postgres double-quote-doubling rule.
# operations.py does not import scaffold, so this introduces no import cycle, and
# the helper has no app-registry side effects, so importing it at module level
# keeps this module cheap to import.
from .operations import _quote_ident


# Marker the assistant/docs/tests look for: backfill is Step 4, app-specific and
# DANGEROUS, so the generated RunPython is always a commented-out STUB.
_BACKFILL_TODO = "TODO(step-4): backfill"


def _model_idents(model):
    """Return the identifiers a migration/DDL needs from a model.

    Returns ``(app_label, model_name, object_name, db_table, label)``. Kept in
    one place so every generator references the model's ``_meta`` consistently.
    """
    meta = model._meta
    return (
        meta.app_label,
        meta.model_name,
        meta.object_name,
        meta.db_table,
        meta.label,
    )


def staged_fk_migration(model):
    """Return migration text for the staged tenant-FK rollout (Steps 3-5).

    The text is a single, self-contained migration *module* that performs the
    safe, non-destructive parts of adding the tenant FK:

    1. ``AddField`` of the tenant ``ForeignKey`` with ``null=True`` so the column
       can be added to a populated table without a table rewrite or a NOT NULL
       violation (Step 3);
    2. a commented-out ``RunPython`` backfill STUB -- the actual backfill (Step 4)
       is cross-schema and entirely app-specific, so it is **never** emitted as
       runnable code; the operator must write and review it;
    3. a clearly-delimited ``AlterField`` flipping the column to ``null=False``
       (Step 5), gated by a comment instructing the operator to move it into a
       *separate* migration that runs only *after* the backfill is verified.

    The migration imports and ``dependencies`` are placeholders the operator
    fills in (the latest migration of the app, plus the tenant model's app).
    """
    from django.conf import settings
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    field = conf.tenant_field()
    tenant_model = settings.TENANT_MODEL

    return '''\
"""Staged tenant-FK rollout for {label} (RLS migration Steps 3-5).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber/rename to follow your latest migration.

This file is a SCAFFOLD. It performs ONLY the safe, non-destructive parts:

  * Step 3: add the tenant FK as ``null=True`` (no table rewrite, no NOT NULL
    violation on an already-populated table).
  * Step 5: an ``AlterField`` to ``null=False`` is included but commented out --
    SPLIT IT INTO A SEPARATE MIGRATION and apply it ONLY AFTER the Step 4
    backfill below has run and you have verified there are no NULL ``{field}_id``
    rows. Applying NOT NULL before the backfill will fail.

The Step 4 backfill is cross-schema and entirely app-specific (DANGEROUS): it is
left as a commented ``RunPython`` STUB for you to implement and review. The
assistant never generates runnable backfill code.
"""

from django.conf import settings
from django.db import migrations, models


# {backfill_todo} the existing rows so every {db_table} row gets the correct
# tenant before the column is made NOT NULL. This is app-specific -- you must map
# each legacy per-schema row to its owning tenant. Implement and review, then
# uncomment the RunPython operation below.
#
# def backfill_tenant(apps, schema_editor):
#     Model = apps.get_model("{app_label}", "{object_name}")
#     # ... map each row to its tenant and set obj.{field}_id ...
#     raise NotImplementedError("Implement the {label} tenant backfill (Step 4).")
#
# def reverse_backfill(apps, schema_editor):
#     # Usually a no-op: clearing the FK would re-create unscoped rows.
#     pass


class Migration(migrations.Migration):

    # TODO: set these to your app's latest migration and the tenant model's app.
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
        migrations.swappable_dependency(settings.TENANT_MODEL),
    ]

    operations = [
        # Step 3: add the tenant FK as NULLABLE so it can be added safely to an
        # already-populated table. matches TenantRLSModel's FK (CASCADE, indexed).
        migrations.AddField(
            model_name="{model_name}",
            name="{field}",
            field=models.ForeignKey(
                to={tenant_model!r},
                on_delete=models.CASCADE,
                db_index=True,
                related_name="+",
                null=True,
            ),
        ),

        # Step 4 (DANGEROUS, app-specific): run the backfill defined above. Keep
        # this COMMENTED until you have implemented and reviewed backfill_tenant.
        # migrations.RunPython(backfill_tenant, reverse_backfill),

        # ---------------------------------------------------------------------
        # Step 5: flip the column to NOT NULL. {backfill_todo} MUST be complete
        # and verified (zero NULL {field}_id rows) BEFORE you apply this. Move
        # this AlterField into its OWN, LATER migration that depends on the
        # backfill migration -- do not apply it in the same step as the backfill.
        # ---------------------------------------------------------------------
        # migrations.AlterField(
        #     model_name="{model_name}",
        #     name="{field}",
        #     field=models.ForeignKey(
        #         to={tenant_model!r},
        #         on_delete=models.CASCADE,
        #         db_index=True,
        #         related_name="+",
        #         null=False,
        #     ),
        # ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        object_name=object_name,
        db_table=db_table,
        field=field,
        tenant_model=tenant_model,
        backfill_todo=_BACKFILL_TODO,
    )


def enable_rls_migration(model):
    """Return migration text enabling RLS + the tenant policy (Step 6).

    Emits a migration whose operations are
    :class:`~django_tenants.rls.operations.EnableRLS` and
    :class:`~django_tenants.rls.operations.CreateTenantPolicy` for the model.
    ``CreateTenantPolicy`` snapshots the tenant field and PK cast at authoring
    time (see its docstring), so the rendered migration is a deterministic record
    of the policy DDL.

    This is the same DDL the safe ``--fix`` / ``model.enable_rls()`` path applies;
    generating it as a migration lets a project that prefers migration-managed
    schema changes carry the enable step in version control instead.
    """
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    field = conf.tenant_field()
    pk_cast = conf.get_tenant_pk_cast()

    return '''\
"""Enable RLS + tenant-isolation policy on {label} (RLS migration Step 6).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber to follow your latest migration.

Apply this ONLY after the {db_table} table has a NOT NULL ``{field}_id`` column
and has been backfilled (Steps 3-5). EnableRLS additionally applies FORCE ROW
LEVEL SECURITY when TENANT_RLS_FORCE is true, so the policy also constrains the
table owner. CreateTenantPolicy builds the same default
TenantPolicy(tenant_field="{field}", pk_cast="{pk_cast}") the framework's
auto-enable path creates, so this is byte-identical to the runtime policy.
"""

from django.db import migrations

from django_tenants.rls import operations as rls_operations


class Migration(migrations.Migration):

    # TODO: set this to your app's latest migration (the one that made
    # {field}_id NOT NULL).
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
    ]

    operations = [
        rls_operations.EnableRLS("{model_name}"),
        rls_operations.CreateTenantPolicy(
            "{model_name}",
            tenant_field="{field}",
            pk_cast="{pk_cast}",
        ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        db_table=db_table,
        field=field,
        pk_cast=pk_cast,
    )


def third_party_policy_sql(table, *, pk_cast="integer"):
    """Return raw ENABLE/FORCE + CREATE POLICY DDL for a third-party ``table``.

    For a table you cannot make inherit ``TenantRLSModel`` (e.g.
    ``authtoken_token``), this emits the same DDL the framework's schema editor
    would emit for the default tenant policy, so the third-party table is policed
    identically to a first-party one (Step 7).

    The USING / WITH CHECK expressions are taken verbatim from
    :meth:`~django_tenants.rls.policies.TenantPolicy.get_using_expression` /
    :meth:`~django_tenants.rls.policies.TenantPolicy.get_check_expression` (the
    InitPlan scalar sub-SELECT form), so the policy is byte-for-byte the framework
    policy. The table is assumed to carry a ``<tenant_field>_id`` column.

    ``pk_cast`` is the Postgres cast suffix matching the tenant model's PK type
    (one of ``integer`` / ``bigint`` / ``uuid`` / ``text``); pass the value from
    ``conf.get_tenant_pk_cast()`` when in doubt. It defaults to ``"integer"`` for
    the common ``AutoField`` / ``BigAutoField``-but-integer case.
    """
    from . import conf
    from .models import _default_policy_name
    from .policies import TenantPolicy

    field = conf.tenant_field()
    policy_name = _default_policy_name(table)
    policy = TenantPolicy(name=policy_name, tenant_field=field, pk_cast=pk_cast)

    using = policy.get_using_expression()
    check = policy.get_check_expression()

    # Quote the table / policy identifiers safely (doubling any embedded quote) so
    # a table name containing a double quote cannot break out of the DDL.
    q_table = _quote_ident(table)
    q_policy = _quote_ident(policy_name)

    # Mirror RLSSchemaEditorMixin.create_policy exactly: AS PERMISSIVE FOR ALL TO
    # public, USING (...) WITH CHECK (...). Identifiers are quoted with double
    # quotes (Postgres standard); the expressions are reused verbatim so they are
    # identical to the framework policy. FORCE matches TENANT_RLS_FORCE's default
    # of true -- without it the table owner silently bypasses the policy.
    return '''\
-- Tenant-isolation RLS policy for third-party table "{table}" (RLS migration Step 7).
--
-- Generated by ``manage.py rls_doctor --generate``. Review, then apply with psql
-- or wrap in a migration RunSQL. This DDL is byte-identical to the policy the
-- framework's schema editor creates for a first-party TenantRLSModel: the
-- USING / WITH CHECK expressions come straight from TenantPolicy, so "{table}"
-- is policed exactly like a managed table.
--
-- PREREQUISITE -- this scaffold emits ONLY the policy. It assumes "{table}"
-- ALREADY has a NOT NULL "{field}_id" column (type matching the tenant PK, cast
-- {pk_cast}) and that it has been backfilled. If the table has no tenant column
-- yet (the usual case for authtoken/auth/sessions), FIRST run, in order:
--   ALTER TABLE {q_table} ADD COLUMN {field}_id <pk type> NULL REFERENCES ...;
--   UPDATE {q_table} SET {field}_id = <owner> WHERE {field}_id IS NULL;  -- backfill
--   ALTER TABLE {q_table} ALTER COLUMN {field}_id SET NOT NULL;
--   -- and tenant-scope any global UNIQUE (e.g. UNIQUE ({field}_id, <key>))
-- See docs/rls_migration.rst "Third-party / non-policied tables". To emit the
-- FULL ordered prerequisite sequence (column + GUC default + FK -> backfill stub
-- -> optional SET NOT NULL -> UNIQUE rewrite -> policy) as one reversible
-- migration step, use isolate_external_table_sql(...) /
-- django_tenants.rls.operations.IsolateExternalTable instead of this policy-only DDL.
-- Drop any existing same-named policy first so this is re-runnable.

ALTER TABLE {q_table} ENABLE ROW LEVEL SECURITY;
-- FORCE so the policy also applies to the table owner role:
ALTER TABLE {q_table} FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS {q_policy} ON {q_table};

CREATE POLICY {q_policy} ON {q_table}
    AS PERMISSIVE FOR ALL TO public
    USING ({using})
    WITH CHECK ({check});
'''.format(
        table=table,
        q_table=q_table,
        field=field,
        pk_cast=pk_cast,
        q_policy=q_policy,
        using=using,
        check=check,
    )


# Postgres column type for each tenant-PK cast suffix; the tenant column added to
# an external table must be the SAME type as the tenant model's PK.
_PK_CAST_TO_COLUMN_TYPE = {
    "integer": "integer",
    "bigint": "bigint",
    "uuid": "uuid",
    "text": "text",
}


def isolate_external_table_sql(table, *, pk_cast="integer", not_null=False,
                               unique_rewrites=None):
    """Return the FULL ordered DDL to tenant-isolate an external ``table`` (Step 7).

    Unlike :func:`third_party_policy_sql` (which emits the *policy* only and assumes
    the tenant column already exists), this emits the **entire prerequisite
    sequence** for a table you cannot subclass (``auth_user``, ``django_session``,
    an external package's table, an M2M *through* table):

    1. ``ADD COLUMN <tenant_field>_id`` of the tenant PK type, with a column
       ``DEFAULT`` reading the tenant GUC
       (``NULLIF(current_setting('<session var>', true), '')::<cast>``) and a
       ``REFERENCES <TENANT_MODEL table> ON DELETE CASCADE`` FK -- added NULLABLE so
       it can be applied to an already-populated table without a NOT NULL violation;
    2. a commented backfill STUB (Step 4, app-specific and DANGEROUS -- never
       emitted as runnable SQL);
    3. an optional ``ALTER COLUMN ... SET NOT NULL`` (only when ``not_null=True``;
       it REQUIRES the Step 2 backfill to have completed first);
    4. for each ``unique_rewrites`` entry ``(old_constraint_name, [new_columns])``,
       a ``DROP CONSTRAINT`` + tenant-scoped ``ADD CONSTRAINT ... UNIQUE`` (Postgres
       checks UNIQUE with RLS bypassed, so every global UNIQUE is a covert channel);
    5. ``ENABLE`` + ``FORCE ROW LEVEL SECURITY`` and the ``CREATE POLICY`` -- whose
       USING / WITH CHECK come verbatim from :class:`~django_tenants.rls.policies.TenantPolicy`
       so it is byte-identical to a first-party model's policy.

    The emitted SQL is a runnable ``psql`` script (the backfill is a commented
    STUB). For a version-controlled, reversible alternative, the header points at
    :class:`~django_tenants.rls.operations.IsolateExternalTable`, which performs the
    same sequence as a single migration operation.

    ``pk_cast`` is the Postgres cast suffix matching the tenant model's PK type
    (``integer`` / ``bigint`` / ``uuid`` / ``text``); pass
    ``conf.get_tenant_pk_cast()`` when in doubt. ``unique_rewrites`` is a list of
    ``(old_constraint_name, [new_columns])`` to rewrite tenant-scoped (typically
    prepend ``<tenant_field>_id``).
    """
    from django.conf import settings
    from . import conf
    from .models import _default_policy_name
    from .policies import TenantPolicy

    field = conf.tenant_field()
    column = "%s_id" % field
    session_var = conf.session_variable()
    tenant_model = settings.TENANT_MODEL

    col_type = _PK_CAST_TO_COLUMN_TYPE.get(pk_cast, pk_cast)

    policy_name = _default_policy_name(table)
    policy = TenantPolicy(name=policy_name, tenant_field=field, pk_cast=pk_cast)
    using = policy.get_using_expression()
    check = policy.get_check_expression()

    q_table = _quote_ident(table)
    q_col = _quote_ident(column)
    q_policy = _quote_ident(policy_name)

    # The column DEFAULT reads the tenant GUC -- same shape as the policy's RHS so
    # rows inserted under an active tenant are auto-stamped and pass WITH CHECK.
    guc_default = "NULLIF(current_setting('%s', true), '')::%s" % (
        session_var.replace("'", "''"), pk_cast,
    )

    # (3) optional SET NOT NULL -- runnable only after the backfill.
    if not_null:
        not_null_sql = (
            "\n-- (3) Tighten to NOT NULL. APPLY ONLY AFTER the backfill above has run\n"
            "--     and you have verified zero NULL %s rows.\n"
            "ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;\n"
            % (column, q_table, q_col)
        )
    else:
        not_null_sql = (
            "\n-- (3) Tighten to NOT NULL once the backfill is complete and verified\n"
            "--     (zero NULL %s rows). Pass not_null=True to emit this, or run:\n"
            "-- ALTER TABLE %s ALTER COLUMN %s SET NOT NULL;\n"
            % (column, q_table, q_col)
        )

    # (4) UNIQUE rewrites -- each leaky global UNIQUE made tenant-scoped.
    if unique_rewrites:
        lines = [
            "\n-- (4) Tenant-scope every global UNIQUE (Postgres checks UNIQUE with RLS\n"
            "--     bypassed, so a tenant-blind UNIQUE is a covert cross-tenant channel)."
        ]
        for old_name, new_columns in unique_rewrites:
            new_name = ("%s_per_tenant" % old_name)[:63]
            cols = ", ".join(_quote_ident(c) for c in new_columns)
            lines.append(
                "ALTER TABLE %s DROP CONSTRAINT %s;"
                % (q_table, _quote_ident(old_name))
            )
            lines.append(
                "ALTER TABLE %s ADD CONSTRAINT %s UNIQUE (%s);"
                % (q_table, _quote_ident(new_name), cols)
            )
        unique_sql = "\n".join(lines) + "\n"
    else:
        unique_sql = (
            "\n-- (4) Tenant-scope EVERY global UNIQUE on this table (Postgres checks\n"
            "--     UNIQUE with RLS bypassed, so each is a covert cross-tenant channel).\n"
            "--     Pass unique_rewrites=[(old_constraint_name, [%r, <key>...]), ...]\n"
            "--     to emit DROP + tenant-scoped ADD for each, e.g.:\n"
            "-- ALTER TABLE %s DROP CONSTRAINT <old_uniq>;\n"
            "-- ALTER TABLE %s ADD CONSTRAINT <old_uniq>_per_tenant UNIQUE (%s, <key>);\n"
            % (column, q_table, q_table, column)
        )

    return '''\
-- Tenant-isolate external table "{table}" under RLS (RLS migration Step 7, FULL sequence).
--
-- Generated by ``manage.py rls_doctor --generate``. Review, then apply with psql,
-- or use django_tenants.rls.operations.IsolateExternalTable("{table}", ...) for a
-- version-controlled, REVERSIBLE migration that performs this same sequence.
--
-- For a table you CANNOT make inherit TenantRLSModel (auth_user, django_session,
-- a third-party / vendored table, an M2M through-table). Such a table otherwise
-- lands unpolicied in the shared public schema and silently shares rows across
-- every tenant. This emits the FULL ordered prerequisite sequence -- the policy
-- (step 5) is byte-identical to the framework's default TenantPolicy.

-- (1) Add the tenant column NULLABLE, with a DEFAULT reading the tenant GUC and a
--     FK to the tenant model. NULLABLE so it can be added to an already-populated
--     table without a NOT NULL violation; the GUC default auto-stamps new rows.
ALTER TABLE {q_table} ADD COLUMN {q_col} {col_type}
    DEFAULT ({guc_default})
    REFERENCES <tenant table for {tenant_model}> (<tenant pk>) ON DELETE CASCADE;

-- (2) {backfill_todo} every existing {table} row to its owning tenant. App-specific
--     and DANGEROUS -- the assistant never emits runnable backfill SQL. Run this
--     under bypass_rls() (no policy exists yet, but make it a habit) BEFORE step 3:
-- UPDATE {q_table} SET {q_col} = <resolve owning tenant> WHERE {q_col} IS NULL;
{not_null_sql}{unique_sql}
-- (5) Enable (+ FORCE so the policy binds the table owner too) RLS and create the
--     tenant-isolation policy -- byte-identical to TenantPolicy(pk_cast="{pk_cast}").
--     Drop any same-named policy first so this is re-runnable.
ALTER TABLE {q_table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE {q_table} FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS {q_policy} ON {q_table};

CREATE POLICY {q_policy} ON {q_table}
    AS PERMISSIVE FOR ALL TO public
    USING ({using})
    WITH CHECK ({check});
'''.format(
        table=table,
        q_table=q_table,
        q_col=q_col,
        col_type=col_type,
        guc_default=guc_default,
        tenant_model=tenant_model,
        pk_cast=pk_cast,
        q_policy=q_policy,
        using=using,
        check=check,
        not_null_sql=not_null_sql,
        unique_sql=unique_sql,
        backfill_todo=_BACKFILL_TODO,
    )


def notnull_migration(model):
    """Migration text to tighten an EXISTING nullable tenant FK to NOT NULL.

    For a model that **already has** the tenant column (so ``AddField`` would be a
    duplicate-column error). Emits the commented backfill STUB (Step 4,
    app-specific -- never runnable) plus the ``AlterField`` to ``null=False``
    (Step 5). ``--generate`` uses this instead of :func:`staged_fk_migration` when
    the tenant FK is present but nullable.
    """
    from django.conf import settings
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    field = conf.tenant_field()
    tenant_model = settings.TENANT_MODEL

    return '''\
"""Tighten {label}.{field} to NOT NULL (RLS migration Steps 4-5).

Generated by ``manage.py rls_doctor --generate``. The {db_table} table ALREADY
has a nullable ``{field}_id`` column, so this does NOT add it -- it backfills and
then makes it NOT NULL. APPLY THE AlterField ONLY AFTER the Step 4 backfill below
has run and you have verified zero NULL ``{field}_id`` rows (ideally as a
separate, later migration that depends on the backfill).
"""

from django.conf import settings
from django.db import migrations, models


# {backfill_todo} every {db_table} row to its owning tenant before NOT NULL.
# App-specific and DANGEROUS -- implement, review, then uncomment the RunPython.
#
# def backfill_tenant(apps, schema_editor):
#     Model = apps.get_model("{app_label}", "{object_name}")
#     raise NotImplementedError("Implement the {label} tenant backfill (Step 4).")


class Migration(migrations.Migration):

    # TODO: depend on your latest migration AND the backfill migration.
    dependencies = [
        # ("{app_label}", "<backfill_migration>"),
    ]

    operations = [
        # migrations.RunPython(backfill_tenant, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="{model_name}",
            name="{field}",
            field=models.ForeignKey(
                to={tenant_model!r},
                on_delete=models.CASCADE,
                db_index=True,
                related_name="+",
                null=False,
            ),
        ),
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        object_name=object_name,
        db_table=db_table,
        field=field,
        tenant_model=tenant_model,
        backfill_todo=_BACKFILL_TODO,
    )


def _unique_source_kind(model, fields):
    """How the UNIQUE over ``fields`` was declared on ``model``.

    Returns ``(kind, name)`` -- ``kind`` is ``"constraint"`` |
    ``"unique_together"`` | ``"field"``; ``name`` is the constraint name for a
    ``Meta.constraints`` ``UniqueConstraint`` (else None). Mirrors
    :func:`checks._unique_fieldsets` so the generated removal operation matches the
    source declaration (a ``RemoveConstraint`` does **not** remove a field-level
    ``unique=True`` or a ``unique_together`` group).
    """
    from django.db.models import UniqueConstraint

    meta = model._meta
    fields_t = tuple(fields)
    for constraint in getattr(meta, "constraints", None) or ():
        if (isinstance(constraint, UniqueConstraint) and constraint.fields
                and tuple(constraint.fields) == fields_t):
            return "constraint", (constraint.name or None)
    unique_together = meta.unique_together or ()
    if unique_together and isinstance(unique_together[0], str):
        unique_together = (unique_together,)
    for group in unique_together:
        if tuple(group) == fields_t:
            return "unique_together", None
    if len(fields_t) == 1:
        try:
            f = meta.get_field(fields_t[0])
            if getattr(f, "unique", False) and not getattr(f, "primary_key", False):
                return "field", None
        except Exception:
            pass
    return "constraint", None


def _render_field_without_unique(model, field_name):
    """Render ``model.field_name`` as migration source with ``unique`` stripped.

    Uses Django's own migration serializer so the field's REAL type and options
    are reproduced (max_length, choices, etc.) instead of a hardcoded placeholder
    that would silently change the column. Best-effort: if the field cannot be
    reconstructed (exotic custom field, import failure) it returns a clearly
    flagged placeholder so the scaffold never crashes.
    """
    fallback = (
        "models.CharField(max_length=255, unique=False)"
        "  # TODO: could not introspect -- replace with your real field"
    )
    try:
        from django.db.migrations.writer import MigrationWriter
        from django.utils.module_loading import import_string

        field = model._meta.get_field(field_name)
        _name, path, args, kwargs = field.deconstruct()
        # unique defaults to False, so dropping it makes the field non-unique.
        kwargs.pop("unique", None)
        field_cls = import_string(path)
        rebuilt = field_cls(*args, **kwargs)
        src, _imports = MigrationWriter.serialize(rebuilt)
        return src
    except Exception:
        return fallback


def _unique_removal_op(model, fields):
    """Return the migration-operation text to drop the old tenant-blind UNIQUE.

    The operation TYPE matches how the UNIQUE was declared (see
    :func:`_unique_source_kind`): ``RemoveConstraint`` for a Meta
    ``UniqueConstraint``, ``AlterUniqueTogether`` for a ``unique_together`` group,
    ``AlterField`` for a field-level ``unique=True``. Field-specific parts are
    left as TODOs (the scaffold cannot reproduce the original field type or your
    full remaining ``unique_together`` set). The returned text is already indented
    to slot into the migration's ``operations`` list.
    """
    model_name = model._meta.model_name
    kind, cname = _unique_source_kind(model, fields)
    fields_t = tuple(fields)
    if kind == "unique_together":
        return (
            "        # Old UNIQUE is a Meta.unique_together group. AlterUniqueTogether\n"
            "        # REPLACES the whole set, so list your REMAINING groups (drop only\n"
            "        # %r); use set() if it was your only group.\n"
            "        migrations.AlterUniqueTogether(\n"
            '            name="%s",\n'
            "            unique_together=set(),  # TODO: your other unique_together groups\n"
            "        )," % (fields_t, model_name)
        )
    if kind == "field":
        fld = fields_t[0] if fields_t else "<field>"
        field_src = _render_field_without_unique(model, fld)
        return (
            "        # Old UNIQUE is a field-level unique=True. The field below is\n"
            "        # reconstructed from your model with unique dropped; review it\n"
            "        # (and add any custom-field import the scaffold could not infer).\n"
            "        migrations.AlterField(\n"
            '            model_name="%s",\n'
            '            name="%s",\n'
            "            field=%s,\n"
            "        )," % (model_name, fld, field_src)
        )
    name = cname or "<old_constraint_name>"
    todo = "" if cname else (
        "        # TODO: replace <old_constraint_name> with the real constraint name.\n"
    )
    return (
        "        # Old UNIQUE is a Meta.constraints UniqueConstraint.\n"
        "%s"
        "        migrations.RemoveConstraint(\n"
        '            model_name="%s",\n'
        '            name="%s",\n'
        "        )," % (todo, model_name, name)
    )


def unique_constraint_migration(model, fields):
    """Return migration text making a UNIQUE constraint tenant-scoped (Step 8).

    PostgreSQL checks UNIQUE constraints with RLS bypassed, so a UNIQUE that omits
    the tenant enforces uniqueness across ALL tenants and leaks cross-tenant row
    existence (check W005). This emits an ``AddConstraint`` of a new
    ``UniqueConstraint`` spanning ``[tenant_field, *fields]`` and a
    ``RemoveConstraint`` of the old, tenant-blind constraint.

    ``fields`` is the offending field set (the tuple from
    ``checks._unique_fieldsets``); the tenant field is prepended (and not
    duplicated if already present). The names of the new and old constraints are
    derived deterministically but flagged as TODOs because the old name depends on
    how the original constraint was declared (a ``unique_together`` /
    ``unique=True`` has an auto-generated name you must look up).
    """
    from . import conf

    app_label, model_name, object_name, db_table, label = _model_idents(model)
    tenant = conf.tenant_field()

    field_list = list(fields)
    # Prepend the tenant field, never duplicating it if the caller already has it.
    scoped = [tenant] + [f for f in field_list if f != tenant]

    scoped_repr = ", ".join(repr(f) for f in scoped)
    suffix = "_".join(field_list) if field_list else "unique"
    new_name = "%s_%s_per_tenant_uniq" % (db_table, suffix)
    # Postgres identifiers cap at 63 bytes; keep the generated name short enough.
    new_name = new_name[:63]

    # The drop operation must match how the old UNIQUE was declared.
    removal_op = _unique_removal_op(model, field_list)

    return '''\
"""Make the UNIQUE on {label} tenant-scoped (RLS migration Step 8).

Generated by ``manage.py rls_doctor --generate``. Review, then drop into
``{app_label}/migrations/`` and renumber to follow your latest migration.

PostgreSQL checks UNIQUE constraints with RLS BYPASSED, so the existing UNIQUE on
{fields!r} enforces uniqueness across ALL tenants and leaks cross-tenant row
existence. This migration replaces it with a tenant-scoped UniqueConstraint over
{scoped!r}.

TODO: also update the model's Meta so makemigrations agrees with this state:
remove the old unique=True / unique_together / UniqueConstraint and add
``models.UniqueConstraint(fields=[{scoped_repr}], name="{new_name}")``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    # TODO: set this to your app's latest migration.
    dependencies = [
        # ("{app_label}", "<previous_migration>"),
    ]

    operations = [
        # Add the tenant-scoped UNIQUE first so uniqueness is never unenforced.
        migrations.AddConstraint(
            model_name="{model_name}",
            constraint=models.UniqueConstraint(
                fields=[{scoped_repr}],
                name="{new_name}",
            ),
        ),
        # Then drop the old, tenant-blind UNIQUE -- with the operation that
        # matches how it was declared (RemoveConstraint / AlterUniqueTogether /
        # AlterField), since a RemoveConstraint cannot remove a field-level
        # unique=True or a unique_together group:
{removal_op}
    ]
'''.format(
        label=label,
        app_label=app_label,
        model_name=model_name,
        fields=tuple(field_list),
        scoped=tuple(scoped),
        scoped_repr=scoped_repr,
        new_name=new_name,
        removal_op=removal_op,
    )
